mqtt:
  binary_sensor:
  - name: "Syncerate test"
    state_topic: "home-assistant/syncerate/command"
    payload_on: "ON"
    availability:
      - topic: "home-assistant/syncerate/available"
        payload_available: "online"
        payload_not_available: "offline"
    qos: 0
